name: Auto Release on Push to Main

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed for pushing tags and creating releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Get latest tag or use v0.1.0
        id: get_tag
        run: |
          tag=$(git tag --sort=-v:refname | head -n 1)
          if [[ -z "$tag" ]]; then
            echo "latest_tag=v0.0.0" >> $GITHUB_OUTPUT
          else
            echo "latest_tag=$tag" >> $GITHUB_OUTPUT
          fi

      - name: Bump tag (patch)
        id: bump_tag
        run: |
          version=${{ steps.get_tag.outputs.latest_tag }}
          version="${version#v}"  # remove v
          IFS='.' read -r major minor patch <<< "$version"
          if [[ "$major" == "0" && "$minor" == "0" && "$patch" == "0" ]]; then
            new_tag="v0.1.0"
          else
            patch=$((patch + 1))
            new_tag="v$major.$minor.$patch"
          fi
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create and push new Git tag
        run: |
          git tag ${{ steps.bump_tag.outputs.new_tag }}
          git push origin ${{ steps.bump_tag.outputs.new_tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump_tag.outputs.new_tag }}
          name: "Release ${{ steps.bump_tag.outputs.new_tag }}"
          body: "Automated release on push to main"
          files: |
            arma-modpack-size-windows.ps1
            arma-modpack-size-linux.sh
